/**
 * userservice.jppol.dk
 * This is a client for the userservice.jppol.dk service @ JP/Politikens Hus
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mail@medielogin.dk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Guid'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Guid'));
  } else {
    // Browser globals (root is window)
    if (!root.Userservicejppoldk) {
      root.Userservicejppoldk = {};
    }
    root.Userservicejppoldk.ChangelogItem = factory(root.Userservicejppoldk.ApiClient, root.Userservicejppoldk.Guid);
  }
}(this, function(ApiClient, Guid) {
  'use strict';




  /**
   * The ChangelogItem model module.
   * @module model/ChangelogItem
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ChangelogItem</code>.
   * A user operation
   * @alias module:model/ChangelogItem
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>ChangelogItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChangelogItem} obj Optional instance to populate.
   * @return {module:model/ChangelogItem} The populated <code>ChangelogItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('UserIdentifier')) {
        obj['UserIdentifier'] = Guid.constructFromObject(data['UserIdentifier']);
      }
      if (data.hasOwnProperty('OperationNumber')) {
        obj['OperationNumber'] = ApiClient.convertToType(data['OperationNumber'], 'Number');
      }
      if (data.hasOwnProperty('Operation')) {
        obj['Operation'] = ApiClient.convertToType(data['Operation'], 'String');
      }
      if (data.hasOwnProperty('EventTime')) {
        obj['EventTime'] = ApiClient.convertToType(data['EventTime'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Guid} UserIdentifier
   */
  exports.prototype['UserIdentifier'] = undefined;
  /**
   * @member {Number} OperationNumber
   */
  exports.prototype['OperationNumber'] = undefined;
  /**
   * @member {module:model/ChangelogItem.OperationEnum} Operation
   */
  exports.prototype['Operation'] = undefined;
  /**
   * @member {String} EventTime
   */
  exports.prototype['EventTime'] = undefined;


  /**
   * Allowed values for the <code>Operation</code> property.
   * @enum {String}
   * @readonly
   */
  exports.OperationEnum = {
    /**
     * value: "Create"
     * @const
     */
    "Create": "Create",
    /**
     * value: "Update"
     * @const
     */
    "Update": "Update",
    /**
     * value: "Delete"
     * @const
     */
    "Delete": "Delete",
    /**
     * value: "RequestDelete"
     * @const
     */
    "RequestDelete": "RequestDelete",
    /**
     * value: "CancelDelete"
     * @const
     */
    "CancelDelete": "CancelDelete"  };


  return exports;
}));


