/**
 * userservice.jppol.dk
 * This is a client for the userservice.jppol.dk service @ JP/Politikens Hus
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mail@medielogin.dk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Userservicejppoldk) {
      root.Userservicejppoldk = {};
    }
    root.Userservicejppoldk.CompleteUsernameChangeRequest = factory(root.Userservicejppoldk.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CompleteUsernameChangeRequest model module.
   * @module model/CompleteUsernameChangeRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CompleteUsernameChangeRequest</code>.
   * Response when username change completion has been attempted
   * @alias module:model/CompleteUsernameChangeRequest
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>CompleteUsernameChangeRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CompleteUsernameChangeRequest} obj Optional instance to populate.
   * @return {module:model/CompleteUsernameChangeRequest} The populated <code>CompleteUsernameChangeRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ChangeUsernameCode')) {
        obj['ChangeUsernameCode'] = ApiClient.convertToType(data['ChangeUsernameCode'], 'String');
      }
      if (data.hasOwnProperty('RequestedUsername')) {
        obj['RequestedUsername'] = ApiClient.convertToType(data['RequestedUsername'], 'String');
      }
      if (data.hasOwnProperty('Password')) {
        obj['Password'] = ApiClient.convertToType(data['Password'], 'String');
      }
    }
    return obj;
  }

  /**
   * The code sent to the user which prooves access to the email account for the new username.
   * @member {String} ChangeUsernameCode
   */
  exports.prototype['ChangeUsernameCode'] = undefined;
  /**
   * The username the user wants to change to.
   * @member {String} RequestedUsername
   */
  exports.prototype['RequestedUsername'] = undefined;
  /**
   * The password of the user who wants to change username. This prooves that the person completing the change request actually is the owner of the account.
   * @member {String} Password
   */
  exports.prototype['Password'] = undefined;



  return exports;
}));


