/**
 * userservice.jppol.dk
 * This is a client for the userservice.jppol.dk service @ JP/Politikens Hus
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mail@medielogin.dk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Userservicejppoldk) {
      root.Userservicejppoldk = {};
    }
    root.Userservicejppoldk.CompleteUsernameChangeResponse = factory(root.Userservicejppoldk.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CompleteUsernameChangeResponse model module.
   * @module model/CompleteUsernameChangeResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CompleteUsernameChangeResponse</code>.
   * Response when username change completion has been attempted
   * @alias module:model/CompleteUsernameChangeResponse
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>CompleteUsernameChangeResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CompleteUsernameChangeResponse} obj Optional instance to populate.
   * @return {module:model/CompleteUsernameChangeResponse} The populated <code>CompleteUsernameChangeResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Code')) {
        obj['Code'] = ApiClient.convertToType(data['Code'], 'String');
      }
    }
    return obj;
  }

  /**
   * the response code
   * @member {module:model/CompleteUsernameChangeResponse.CodeEnum} Code
   */
  exports.prototype['Code'] = undefined;


  /**
   * Allowed values for the <code>Code</code> property.
   * @enum {String}
   * @readonly
   */
  exports.CodeEnum = {
    /**
     * value: "Success"
     * @const
     */
    "Success": "Success",
    /**
     * value: "IncorrectPassword"
     * @const
     */
    "IncorrectPassword": "IncorrectPassword",
    /**
     * value: "IncorrectChangeUsernameCode"
     * @const
     */
    "IncorrectChangeUsernameCode": "IncorrectChangeUsernameCode",
    /**
     * value: "UnexpectedNewUsername"
     * @const
     */
    "UnexpectedNewUsername": "UnexpectedNewUsername",
    /**
     * value: "NoSuchUser"
     * @const
     */
    "NoSuchUser": "NoSuchUser",
    /**
     * value: "RequestExpired"
     * @const
     */
    "RequestExpired": "RequestExpired"  };


  return exports;
}));


