/**
 * userservice.jppol.dk
 * This is a client for the userservice.jppol.dk service @ JP/Politikens Hus
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mail@medielogin.dk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EmailValidationCode'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EmailValidationCode'));
  } else {
    // Browser globals (root is window)
    if (!root.Userservicejppoldk) {
      root.Userservicejppoldk = {};
    }
    root.Userservicejppoldk.EmailValidationResult = factory(root.Userservicejppoldk.ApiClient, root.Userservicejppoldk.EmailValidationCode);
  }
}(this, function(ApiClient, EmailValidationCode) {
  'use strict';




  /**
   * The EmailValidationResult model module.
   * @module model/EmailValidationResult
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>EmailValidationResult</code>.
   * @alias module:model/EmailValidationResult
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>EmailValidationResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EmailValidationResult} obj Optional instance to populate.
   * @return {module:model/EmailValidationResult} The populated <code>EmailValidationResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('validatedEmail')) {
        obj['validatedEmail'] = ApiClient.convertToType(data['validatedEmail'], 'String');
      }
      if (data.hasOwnProperty('isValidEmail')) {
        obj['isValidEmail'] = ApiClient.convertToType(data['isValidEmail'], 'Boolean');
      }
      if (data.hasOwnProperty('validationResultCode')) {
        obj['validationResultCode'] = EmailValidationCode.constructFromObject(data['validationResultCode']);
      }
      if (data.hasOwnProperty('validationResultMessage')) {
        obj['validationResultMessage'] = ApiClient.convertToType(data['validationResultMessage'], 'String');
      }
    }
    return obj;
  }

  /**
   * Which email was validated?
   * @member {String} validatedEmail
   */
  exports.prototype['validatedEmail'] = undefined;
  /**
   * 'true' for valid emails, 'false' if email is not allowed.
   * @member {Boolean} isValidEmail
   */
  exports.prototype['isValidEmail'] = undefined;
  /**
   * @member {module:model/EmailValidationCode} validationResultCode
   */
  exports.prototype['validationResultCode'] = undefined;
  /**
   * Additional information about the result.
   * @member {String} validationResultMessage
   */
  exports.prototype['validationResultMessage'] = undefined;



  return exports;
}));


