/**
 * userservice.jppol.dk
 * This is a client for the userservice.jppol.dk service @ JP/Politikens Hus
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mail@medielogin.dk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MapItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MapItem'));
  } else {
    // Browser globals (root is window)
    if (!root.Userservicejppoldk) {
      root.Userservicejppoldk = {};
    }
    root.Userservicejppoldk.PropertyBag = factory(root.Userservicejppoldk.ApiClient, root.Userservicejppoldk.MapItem);
  }
}(this, function(ApiClient, MapItem) {
  'use strict';




  /**
   * The PropertyBag model module.
   * @module model/PropertyBag
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PropertyBag</code>.
   * Properties of a user.
   * @alias module:model/PropertyBag
   * @class
   * @extends Object
   */
  var exports = function() {
    var _this = this;







    return _this;
  };

  /**
   * Constructs a <code>PropertyBag</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PropertyBag} obj Optional instance to populate.
   * @return {module:model/PropertyBag} The populated <code>PropertyBag</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ApiClient.constructFromObject(data, obj, 'MapItem');

      if (data.hasOwnProperty('FirstName')) {
        obj['FirstName'] = ApiClient.convertToType(data['FirstName'], 'String');
      }
      if (data.hasOwnProperty('LastName')) {
        obj['LastName'] = ApiClient.convertToType(data['LastName'], 'String');
      }
      if (data.hasOwnProperty('BirthDate')) {
        obj['BirthDate'] = ApiClient.convertToType(data['BirthDate'], 'String');
      }
      if (data.hasOwnProperty('Branding')) {
        obj['Branding'] = ApiClient.convertToType(data['Branding'], 'String');
      }
      if (data.hasOwnProperty('SubscriptionID_POL')) {
        obj['SubscriptionID_POL'] = ApiClient.convertToType(data['SubscriptionID_POL'], ['String']);
      }
      if (data.hasOwnProperty('PhonePrimary')) {
        obj['PhonePrimary'] = ApiClient.convertToType(data['PhonePrimary'], 'String');
      }
    }
    return obj;
  }

  /**
   * Users first name
   * @member {String} FirstName
   */
  exports.prototype['FirstName'] = undefined;
  /**
   * Users last name
   * @member {String} LastName
   */
  exports.prototype['LastName'] = undefined;
  /**
   * @member {String} BirthDate
   */
  exports.prototype['BirthDate'] = undefined;
  /**
   * Defines the welcome/confirmation e-mail sent to the user upon creation.
   * @member {String} Branding
   */
  exports.prototype['Branding'] = undefined;
  /**
   * @member {Array.<String>} SubscriptionID_POL
   */
  exports.prototype['SubscriptionID_POL'] = undefined;
  /**
   * @member {String} PhonePrimary
   */
  exports.prototype['PhonePrimary'] = undefined;



  return exports;
}));


