/**
 * userservice.jppol.dk
 * This is a client for the userservice.jppol.dk service @ JP/Politikens Hus
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mail@medielogin.dk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Guid', 'model/Userstate'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Guid'), require('./Userstate'));
  } else {
    // Browser globals (root is window)
    if (!root.Userservicejppoldk) {
      root.Userservicejppoldk = {};
    }
    root.Userservicejppoldk.ReservationResponse = factory(root.Userservicejppoldk.ApiClient, root.Userservicejppoldk.Guid, root.Userservicejppoldk.Userstate);
  }
}(this, function(ApiClient, Guid, Userstate) {
  'use strict';




  /**
   * The ReservationResponse model module.
   * @module model/ReservationResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ReservationResponse</code>.
   * Result of the reservation
   * @alias module:model/ReservationResponse
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>ReservationResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReservationResponse} obj Optional instance to populate.
   * @return {module:model/ReservationResponse} The populated <code>ReservationResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Identifier')) {
        obj['Identifier'] = Guid.constructFromObject(data['Identifier']);
      }
      if (data.hasOwnProperty('IsNewUser')) {
        obj['IsNewUser'] = ApiClient.convertToType(data['IsNewUser'], 'Boolean');
      }
      if (data.hasOwnProperty('HasLogin')) {
        obj['HasLogin'] = ApiClient.convertToType(data['HasLogin'], 'Boolean');
      }
      if (data.hasOwnProperty('Version')) {
        obj['Version'] = ApiClient.convertToType(data['Version'], 'Number');
      }
      if (data.hasOwnProperty('State')) {
        obj['State'] = Userstate.constructFromObject(data['State']);
      }
    }
    return obj;
  }

  /**
   * Identifier of the user
   * @member {module:model/Guid} Identifier
   */
  exports.prototype['Identifier'] = undefined;
  /**
   * True if the request caused a new record to be created in userservice.
   * @member {Boolean} IsNewUser
   */
  exports.prototype['IsNewUser'] = undefined;
  /**
   * Can the user log in or will the profile be treated as a non-existing user when the service is accessed.
   * @member {Boolean} HasLogin
   */
  exports.prototype['HasLogin'] = undefined;
  /**
   * The current version of the user
   * @member {Number} Version
   */
  exports.prototype['Version'] = undefined;
  /**
   * @member {module:model/Userstate} State
   */
  exports.prototype['State'] = undefined;



  return exports;
}));


