/**
 * userservice.jppol.dk
 * This is a client for the userservice.jppol.dk service @ JP/Politikens Hus
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mail@medielogin.dk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Guid'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Guid'));
  } else {
    // Browser globals (root is window)
    if (!root.Userservicejppoldk) {
      root.Userservicejppoldk = {};
    }
    root.Userservicejppoldk.SetPasswordResponse = factory(root.Userservicejppoldk.ApiClient, root.Userservicejppoldk.Guid);
  }
}(this, function(ApiClient, Guid) {
  'use strict';




  /**
   * The SetPasswordResponse model module.
   * @module model/SetPasswordResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SetPasswordResponse</code>.
   * A password validation response. For matched users this object will contain additional information useful to display messages to the user etc.
   * @alias module:model/SetPasswordResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>SetPasswordResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SetPasswordResponse} obj Optional instance to populate.
   * @return {module:model/SetPasswordResponse} The populated <code>SetPasswordResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('UserIdentifier')) {
        obj['UserIdentifier'] = Guid.constructFromObject(data['UserIdentifier']);
      }
      if (data.hasOwnProperty('Response')) {
        obj['Response'] = ApiClient.convertToType(data['Response'], 'String');
      }
    }
    return obj;
  }

  /**
   * Identifier of the user matching both username and password. Will be false when password is incorrect even though a match for username was found. If you need to lookup users, you should use the 'lookup' method.
   * @member {module:model/Guid} UserIdentifier
   */
  exports.prototype['UserIdentifier'] = undefined;
  /**
   * @member {module:model/SetPasswordResponse.ResponseEnum} Response
   */
  exports.prototype['Response'] = undefined;


  /**
   * Allowed values for the <code>Response</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ResponseEnum = {
    /**
     * value: "InvalidPassword"
     * @const
     */
    "InvalidPassword": "InvalidPassword",
    /**
     * value: "Success"
     * @const
     */
    "Success": "Success",
    /**
     * value: "NoSuchUser"
     * @const
     */
    "NoSuchUser": "NoSuchUser"  };


  return exports;
}));


