/**
 * userservice.jppol.dk
 * This is a client for the userservice.jppol.dk service @ JP/Politikens Hus
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mail@medielogin.dk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Guid', 'model/PropertyBag'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Guid'), require('./PropertyBag'));
  } else {
    // Browser globals (root is window)
    if (!root.Userservicejppoldk) {
      root.Userservicejppoldk = {};
    }
    root.Userservicejppoldk.UserForUpdate = factory(root.Userservicejppoldk.ApiClient, root.Userservicejppoldk.Guid, root.Userservicejppoldk.PropertyBag);
  }
}(this, function(ApiClient, Guid, PropertyBag) {
  'use strict';




  /**
   * The UserForUpdate model module.
   * @module model/UserForUpdate
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>UserForUpdate</code>.
   * The user object for updates. It is not necessarily possible to update all values returned by a GET.
   * @alias module:model/UserForUpdate
   * @class
   * @param identifier {module:model/Guid} 
   * @param properties {module:model/PropertyBag} 
   */
  var exports = function(identifier, properties) {
    var _this = this;

    _this['Identifier'] = identifier;
    _this['Properties'] = properties;
  };

  /**
   * Constructs a <code>UserForUpdate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserForUpdate} obj Optional instance to populate.
   * @return {module:model/UserForUpdate} The populated <code>UserForUpdate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Identifier')) {
        obj['Identifier'] = Guid.constructFromObject(data['Identifier']);
      }
      if (data.hasOwnProperty('Properties')) {
        obj['Properties'] = PropertyBag.constructFromObject(data['Properties']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Guid} Identifier
   */
  exports.prototype['Identifier'] = undefined;
  /**
   * @member {module:model/PropertyBag} Properties
   */
  exports.prototype['Properties'] = undefined;



  return exports;
}));


