/**
 * userservice.jppol.dk
 * This is a client for the userservice.jppol.dk service @ JP/Politikens Hus
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mail@medielogin.dk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PropertyBag'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PropertyBag'));
  } else {
    // Browser globals (root is window)
    if (!root.Userservicejppoldk) {
      root.Userservicejppoldk = {};
    }
    root.Userservicejppoldk.UserHistoryItem = factory(root.Userservicejppoldk.ApiClient, root.Userservicejppoldk.PropertyBag);
  }
}(this, function(ApiClient, PropertyBag) {
  'use strict';




  /**
   * The UserHistoryItem model module.
   * @module model/UserHistoryItem
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>UserHistoryItem</code>.
   * Version is a .NET Tick identifying the event time. Properties contain user state at the given moment.
   * @alias module:model/UserHistoryItem
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>UserHistoryItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserHistoryItem} obj Optional instance to populate.
   * @return {module:model/UserHistoryItem} The populated <code>UserHistoryItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Version')) {
        obj['Version'] = ApiClient.convertToType(data['Version'], 'Number');
      }
      if (data.hasOwnProperty('Properties')) {
        obj['Properties'] = PropertyBag.constructFromObject(data['Properties']);
      }
    }
    return obj;
  }

  /**
   * @member {Number} Version
   */
  exports.prototype['Version'] = undefined;
  /**
   * @member {module:model/PropertyBag} Properties
   */
  exports.prototype['Properties'] = undefined;



  return exports;
}));


