/**
 * userservice.jppol.dk
 * This is a client for the userservice.jppol.dk service @ JP/Politikens Hus
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mail@medielogin.dk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Userstate'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Userstate'));
  } else {
    // Browser globals (root is window)
    if (!root.Userservicejppoldk) {
      root.Userservicejppoldk = {};
    }
    root.Userservicejppoldk.ValidatePasswordResponse = factory(root.Userservicejppoldk.ApiClient, root.Userservicejppoldk.Userstate);
  }
}(this, function(ApiClient, Userstate) {
  'use strict';




  /**
   * The ValidatePasswordResponse model module.
   * @module model/ValidatePasswordResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ValidatePasswordResponse</code>.
   * A password validation response. For matched users this object will contain additional information useful to display messages to the user etc.
   * @alias module:model/ValidatePasswordResponse
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>ValidatePasswordResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ValidatePasswordResponse} obj Optional instance to populate.
   * @return {module:model/ValidatePasswordResponse} The populated <code>ValidatePasswordResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('IsAuthorized')) {
        obj['IsAuthorized'] = ApiClient.convertToType(data['IsAuthorized'], 'Boolean');
      }
      if (data.hasOwnProperty('UserCreated')) {
        obj['UserCreated'] = ApiClient.convertToType(data['UserCreated'], 'String');
      }
      if (data.hasOwnProperty('FoundMatchingUser')) {
        obj['FoundMatchingUser'] = ApiClient.convertToType(data['FoundMatchingUser'], 'Boolean');
      }
      if (data.hasOwnProperty('Identifier')) {
        obj['Identifier'] = ApiClient.convertToType(data['Identifier'], 'String');
      }
      if (data.hasOwnProperty('IsActivated')) {
        obj['IsActivated'] = ApiClient.convertToType(data['IsActivated'], 'Boolean');
      }
      if (data.hasOwnProperty('IsLockedOut')) {
        obj['IsLockedOut'] = ApiClient.convertToType(data['IsLockedOut'], 'Boolean');
      }
      if (data.hasOwnProperty('UserState')) {
        obj['UserState'] = Userstate.constructFromObject(data['UserState']);
      }
    }
    return obj;
  }

  /**
   * True if the user should be considered logged in based on the input
   * @member {Boolean} IsAuthorized
   */
  exports.prototype['IsAuthorized'] = undefined;
  /**
   * The date and time where the user was created.
   * @member {String} UserCreated
   */
  exports.prototype['UserCreated'] = undefined;
  /**
   * True when a user with the given username was found. Will be true even when password did not match.
   * @member {Boolean} FoundMatchingUser
   */
  exports.prototype['FoundMatchingUser'] = undefined;
  /**
   * Identifier of the user matching both username and password. Will be false when password is incorrect even though a match for username was found. If you need to lookup users, you should use the 'lookup' method.
   * @member {String} Identifier
   */
  exports.prototype['Identifier'] = undefined;
  /**
   * True when the user has at some point confirmed ownership to the account.
   * @member {Boolean} IsActivated
   */
  exports.prototype['IsActivated'] = undefined;
  /**
   * True when the user is locked out due to too many wrong password attempts.
   * @member {Boolean} IsLockedOut
   */
  exports.prototype['IsLockedOut'] = undefined;
  /**
   * @member {module:model/Userstate} UserState
   */
  exports.prototype['UserState'] = undefined;



  return exports;
}));


