/**
 * userservice.jppol.dk
 * This is a client for the userservice.jppol.dk service @ JP/Politikens Hus
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mail@medielogin.dk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/UserHistory'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/UserHistory'));
  } else {
    // Browser globals (root is window)
    if (!root.Userservicejppoldk) {
      root.Userservicejppoldk = {};
    }
    root.Userservicejppoldk.UserHistoryApi = factory(root.Userservicejppoldk.ApiClient, root.Userservicejppoldk.UserHistory);
  }
}(this, function(ApiClient, UserHistory) {
  'use strict';

  /**
   * UserHistory service.
   * @module api/UserHistoryApi
   * @version 1.0.0
   */

  /**
   * Constructs a new UserHistoryApi. 
   * @alias module:api/UserHistoryApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getHistory operation.
     * @callback module:api/UserHistoryApi~getHistoryCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UserHistory} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get users property history
     * 
     * @param {String} useridentifier 
     * @param {module:api/UserHistoryApi~getHistoryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UserHistory}
     */
    this.getHistory = function(useridentifier, callback) {
      var postBody = null;

      // verify the required parameter 'useridentifier' is set
      if (useridentifier === undefined || useridentifier === null) {
        throw new Error("Missing the required parameter 'useridentifier' when calling getHistory");
      }


      var pathParams = {
        'useridentifier': useridentifier
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['clientAccess', 'userAccess'];
      var contentTypes = ['application/json+jsondate'];
      var accepts = ['application/json+jsondate'];
      var returnType = UserHistory;

      return this.apiClient.callApi(
        '/ssouser.svc/history/{useridentifier}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
