/**
 * userservice.jppol.dk
 * This is a client for the userservice.jppol.dk service @ JP/Politikens Hus
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mail@medielogin.dk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Userservicejppoldk);
  }
}(this, function(expect, Userservicejppoldk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Userservicejppoldk.ValidatePasswordResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ValidatePasswordResponse', function() {
    it('should create an instance of ValidatePasswordResponse', function() {
      // uncomment below and update the code to test ValidatePasswordResponse
      //var instane = new Userservicejppoldk.ValidatePasswordResponse();
      //expect(instance).to.be.a(Userservicejppoldk.ValidatePasswordResponse);
    });

    it('should have the property isAuthorized (base name: "IsAuthorized")', function() {
      // uncomment below and update the code to test the property isAuthorized
      //var instane = new Userservicejppoldk.ValidatePasswordResponse();
      //expect(instance).to.be();
    });

    it('should have the property userCreated (base name: "UserCreated")', function() {
      // uncomment below and update the code to test the property userCreated
      //var instane = new Userservicejppoldk.ValidatePasswordResponse();
      //expect(instance).to.be();
    });

    it('should have the property foundMatchingUser (base name: "FoundMatchingUser")', function() {
      // uncomment below and update the code to test the property foundMatchingUser
      //var instane = new Userservicejppoldk.ValidatePasswordResponse();
      //expect(instance).to.be();
    });

    it('should have the property identifier (base name: "Identifier")', function() {
      // uncomment below and update the code to test the property identifier
      //var instane = new Userservicejppoldk.ValidatePasswordResponse();
      //expect(instance).to.be();
    });

    it('should have the property isActivated (base name: "IsActivated")', function() {
      // uncomment below and update the code to test the property isActivated
      //var instane = new Userservicejppoldk.ValidatePasswordResponse();
      //expect(instance).to.be();
    });

    it('should have the property isLockedOut (base name: "IsLockedOut")', function() {
      // uncomment below and update the code to test the property isLockedOut
      //var instane = new Userservicejppoldk.ValidatePasswordResponse();
      //expect(instance).to.be();
    });

    it('should have the property userState (base name: "UserState")', function() {
      // uncomment below and update the code to test the property userState
      //var instane = new Userservicejppoldk.ValidatePasswordResponse();
      //expect(instance).to.be();
    });

  });

}));
